# basic info
name: Kenneth Hung
department: Department of Mathematics
university: UC Berkeley
keywords: Kenneth, Hung, Berkeley, math, mathematics, stat, statistics
url: http://kenhung.me

# contacts
email: me@kenhung.me
github: kenhungkk
linkedin: kenkhung
twitter: kenhungkk

# technical setting
permalink: /:categories/:year-:month-:day-:title.html
markdown: kramdown
mathjax: true