project:
  type: website

website:
  title: "Kenneth Hung"
  description: Kenneth Hung's website
  site-url: https://kenhung.me
  navbar:
    left:
      - text: Home
        href: index.qmd
      - href: research.qmd
      - href: teaching.qmd
      - href: posts.qmd
  page-footer:
    center:
      - icon: envelope-fill
        href: mailto:me@kenhung.me
        aria-label: "email: me@kenhung.me"
      - icon: github
        href: https://github.com/kenhungkk
        aria-label: "github: kenhungkk"
      - icon: mortarboard-fill
        href: https://scholar.google.com/citations?user=G0x9hZkAAAAJ&hl=en
        aria-label: "google scholar"
      - icon: twitter
        href: https://twitter.com/kenhungkk
        aria-label: "twitter: @kenhungkk"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

code-line-numbers: true